# Generated by Django 5.0.2 on 2024-03-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
