# Generated by Django 5.0.2 on 2024-03-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_book', '0003_alter_book_author_alter_book_publisher'),
        ('core_genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='core_genre.genre'),
        ),
    ]
